backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "src/assets"
public_folder: "/assets"


collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    media_folder: "/images"
    public_folder: "/content/blog/images"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", default: ["News", "Announcements"], required: false }
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: 'Body', name: 'body', widget: 'markdown' }
